[package]
name = "solana_escrow"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "=1.8.1"
thiserror = "=1.0.30"
spl-token = "=3.2.0"

[lib]
crate-type = ["cdylib", "lib"]
